#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Jun 07 20:15:24 CEST 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=16
shaderPack=ComplementaryReimagined_r5.5.1.zip
