name = "Bat Cave Vanilla Worlds 2"
author = "JonnyB and meludoge"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71c762fdb2b37643ba1e764d38e0c8911a6070617b1e16239bfa0afb691521d8"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = ["1.21.5"]
