name = "Bat Cave Vanilla Worlds 2"
author = "JonnyB and meludoge"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "511d287d7a2ae79f4b277e6e84f821bd4455c76a157b0566eef2bbd12fed2407"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = ["1.21.5"]
