name = "Bat Cave Vanilla Worlds 2"
author = "JonnyB and meludoge"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11ce819f8a51a29efa0bdb3697c81c5b2d8a0b685d8aba662951fce20f384a1a"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = ["1.21.5"]
