name = "UwUcraft"
author = "meludoge"
version = "5.10.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b966780c289cf183d6695527645e301346f7db1c82092da0366e12b5bb8b832"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
