name = "UwUcraft"
author = "meludoge"
version = "5.10.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7412e4af5f5692c2e0d3cc66d4984cc6ce90b944463b93671030d382b7255b7"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
