name = "UwUcraft"
author = "meludoge"
version = "5.10.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "798146e1e286d0f6e7fe3284e0570d7de74f9e162a3f99b95dbad8e354336a62"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
