name = "UwUcraft"
author = "meludoge"
version = "5.10.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4185959d1604d43aaaf0cd1bc7969496aedff02d09b0db04c0577e8f22d7eea"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
