name = "UwUcraft"
author = "meludoge"
version = "5.10.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47aa8f21274f8d31422efcba2da337d23d84810d0f8b714bcf82e0cf1245a877"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
