name = "UwUcraft"
author = "meludoge"
version = "5.10.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a82995e3952440ffdb5fb4d5a5bd3b1e05f8dfa27c341b7e6d55eef5274fe463"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
