name = "UwUcraft"
author = "meludoge"
version = "5.10.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2a5687fd0d6f2fed4c1b49a4bfd5b61daa63b81510116c14f54d6754eb30559"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
