name = "UwUcraft"
author = "meludoge"
version = "5.10.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a13fe6f069a6aae1443523b55c5b8594fc8e8af5833eb86aad0f458d1c7d9c84"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
