name = "UwUcraft"
author = "meludoge"
version = "5.10.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ab5ca421144f5618367e2397c8927c6bd10743a03a9a59803a24eb402aea1bd"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
